


database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db?autoReconnect=true&useSSL=false
  user: bryant 
  password: bryant 
  maxWaitForConnection: 10s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
